### ISSUE TITLE
Post ETN V6 Fork - Nicehash and Claymore issues connecting to ETN pools

### ISSUE THREAD

**Issue by mannie65** [electroneum/electroneum#259] opened 2018-06-07 15:10 UTC
Hello ETN Devs, I submitted this via Telegram a few days ago to one of the admin who passed it on to the devs, but thought I would also submit this here so any other having issues have a workaround.

Like other pool owners I applied the May 2018 V6 updates from ETN to my pool http://etn.thorshammer.cc well before the fork. Everything was fine until block 307500 (V6 Fork) at which point ETHOS mining rigs running Claymore-XMR 11.3 stopped working. We also got complaints from Nicehash users that they could no longer submit NH to our pool. I thought it might have been an issue with this pool software post fork so I then installed a pool based on ETN own GitHub release, and had the exact same issues. This issue DOES NOT exist in any of our other Cryptonight coin pools that we have that have forked. Anyway after a lot of testing and troubleshooting we identified that the problem goes away if we used ETN integrated wallet address, as opposed to a standard ETN address. This resolved the issue with both Nicehash and ETHOS/Claymore. Why I am not 100% sure - would love to hear from the ETN devs, but the problem ONLY happens with ETN V6 post fork.

Workaround for anyone with this issue - use ETN integrated addresses for your wallets 

I am happy to report that using the integrated address works 100% fine, and we have even popped a block post fork without issues.

I suspect that the intAddressPrefix setting in the config.json might need to be modified and this might fix this, something I will look into a little later (but this setting does not exist in the ETN pool software which also has the issue)

**Comment by andrepatta** [comment] 2018-06-07 16:54
Hi @mannie65,

Thanks for your time investigating this. We're working on the issue.

Thanks

**Comment by mannie65** [comment] 2018-06-08 10:21
@andrepatta Just an update - well overnight my Ethos/Claymore-XMR rigs stopped working even with integrated address, and just tried a test NiceHash and it wont fire up. Now I am totally perplexed :-(

**Comment by Cideg** [comment] 2018-06-09 10:14
I can confirm the error, unfortunately it is not possible to unlock blocks. Once the error is found, the pool will find no more blocks. The demon is extremely flawed. There is a clean update of the need, I hope you will soon meet the community.

Is there a way to allow small pools to unlock fast and fluffy-blocks?

**Comment by mannie65** [comment] 2018-06-11 14:15
@andrepatta I have some additional info.

So over the past few days the issue has gone away and come back. Right now the issue is present.
It was OK up until an hour or so ago

All i can put it down to is an assumption that the Overall Network Hash or Diff comes into play. When Nethash was around 85-95Mh/s and Diff was 10B -11B it was working fine. Now we are at 106Mh/s and 12.5B Diff, and all of the sudden problem has re-appeared. 

This is now getting crazy , please look into this - I have just lost 100Kh/s of hash from my pool because of it, as my ETHOS rigs now getting the error again, and I just tested Nicehash and it doesn't work either.

I will now be forced to point my hash to another coins pools - as I have no option.

Need someone to give us a clue as to whats happening please

**Comment by andrepatta** [comment] 2018-06-11 14:29
@mannie65 I highly doubt this issue is related to the current network difficulty. Could you please start the daemon with --log-level 2 (or even 3) and send me the log file once the problem is detected?

Would be good to have a similar log for the pool software as well.

**Comment by andrepatta** [comment] 2018-06-11 14:36
@mannie65 Can you please send me your Telegram ID so we can have a more effective conversation?

**Comment by mannie65** [comment] 2018-06-11 14:42
@andrepatta @Crypto_Kangaroo (https://t.me/Crypto_Kangaroo)

**Comment by andrepatta** [comment] 2018-06-14 19:12
Issue fixed with #262.

**Closed as completed** 2018-07-10 12:00 UTC
